# 주식 데이터:
 >

In [4]:
!pip install finance-datareader

Collecting finance-datareader
  Downloading finance_datareader-0.9.96-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from finance-datareader) (4.12.3)
Collecting lxml (from finance-datareader)
  Downloading lxml-6.0.0-cp39-cp39-win_amd64.whl.metadata (6.8 kB)
Requirement already satisfied: pandas>=1.1.0 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from finance-datareader) (2.2.3)
Collecting plotly (from finance-datareader)
  Downloading plotly-6.2.0-py3-none-any.whl.metadata (8.5 kB)
Collecting requests-file (from finance-datareader)
  Downloading requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: requests>=2.3.0 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from finance-datareader) (2.32.3)
Collecting tqdm (from finance-datareader)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->finance-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->finance-datareader) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->finance-datareader) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->finance-datareader) (2025.1.31)
Requirement already satisfied: soupsieve>1.2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from beautifulsoup4->finance-datareader) (2.5)
Collecting narwhals>=1.15.1 (from plotly->finance-datareader)
  Downloading narwhals-1.44.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from plotly->finance-datareader) (24.2)
Requirement already satisfied: colorama in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from tqdm->finance-datareader) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.0->finance-datareader) (1.17.0)
Downloading finance_datareader-0.9.96-py3-none-any.whl (48 kB)
Downloading lxml-6.0.0-cp39-cp39-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------ --------------------------- 1.3/4.0 MB 7.4 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.7 MB/s eta 0:00:00
Downloading plotly-6.2.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.6 MB 7.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.6 MB 6.6 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.6 MB 6.7 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.6 MB 6.2 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.6 MB 5.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 5.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 5.8 MB/s eta 0:00:00
Downloading requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading narwhals-1.44.0-py3-none-any.whl (365 kB)
Installing collected packages: tqdm, narwhals, lxml, requests-file, plotly, finance-datareader
Successfully installed finance-datareader-0.9.96 lxml-6.0.0 narwhals-1.44.0 plotly-6.2.0 requests-file-2.1.0 tqdm-4.67.1

In [5]:
import FinanceDataReader as fdr

In [7]:
KP_stock_list = fdr.StockListing("KOSPI") #코스피 종목 목록

display(KP_stock_list)

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,60800,1,600,1.00,60100,61600,60000,17340470,1053939281525,359913985657600,5919637922,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,284000,2,-9000,-3.07,288000,294500,281000,5134863,1469227568381,206752671660000,728002365,STK
2,207940,KR7207940008,삼성바이오로직스,KOSPI,,996000,2,-3000,-0.30,1004000,1005000,993000,38057,37915832500,70889304000000,71174000,STK
3,373220,KR7373220003,LG에너지솔루션,KOSPI,,288000,2,-9000,-3.03,297500,297500,287000,219699,63656967000,67392000000000,234000000,STK
4,105560,KR7105560007,KB금융,KOSPI,,110600,1,700,0.64,110000,112300,109500,1045704,115861647400,42189708591800,381462103,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,004415,KR7004411005,서울식품우,KOSPI,,1265,1,24,1.93,1239,1265,1239,7070,8872712,2813992500,2224500,STK
958,014915,KR7014911002,성문전자우,KOSPI,,4655,2,-15,-0.32,4605,4660,4600,682,3139840,2793000000,600000,STK
959,001527,KR7001522002,동양2우B,KOSPI,,8630,1,210,2.49,8500,8630,8500,91,774960,2662950470,308569,STK
960,001525,KR7001521004,동양우,KOSPI,,4230,1,125,3.05,4200,4230,4200,1114,4684830,2613002130,617731,STK
961,002787,KR7002782001,진흥기업2우B,KOSPI,,7900,1,10,0.13,8010,8010,7870,7945,62685510,2328983200,294808,STK

In [10]:
sp_data = fdr.DataReader("005380", "2025-01-01", "2025-06-27")
display(sp_data)

              Open    High     Low   Close   Volume    Change
Date
2025-01-02  212000  216000  210500  211500   437773 -0.002358
2025-01-03  211500  215000  211000  213000   456107  0.007092
2025-01-06  213000  213500  207000  211500   782307 -0.007042
2025-01-07  211500  214000  210500  211000   511955 -0.002364
2025-01-08  209500  215500  209000  213500   603411  0.011848
...            ...     ...     ...     ...      ...       ...
2025-06-23  205500  206000  200500  201500   935001 -0.040476
2025-06-24  206500  208000  203000  206000   718116  0.022333
2025-06-25  206500  221500  206000  217000  1789517  0.053398
2025-06-26  214500  215000  208000  209500   814616 -0.034562
2025-06-27  211000  211000  203000  205000   764378 -0.021480

[117 rows x 6 columns]

In [11]:
SP500_stock_list = fdr.StockListing("SP500") #미국
display(SP500_stock_list)

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,A. O. Smith,Industrials,Building Products
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment
3,ABBV,AbbVie,Health Care,Biotechnology
4,ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment
502,ZTS,Zoetis,Health Care,Pharmaceuticals

# 주요 지수 데이터

In [12]:
KP_idx_data = fdr.DataReader("KS11", "2025-01-01", "2025-06-27")
display(KP_idx_data)

,Open,High,Low,Close,Volume,Change,UpDown,Comp,Amount,MarCap
Date,,,,,,,,,,
2025-01-02,2400.87,2410.99,2386.84,2398.94,350691927,-0.0002,2,-0.55,6958648750080,1963454272081159
2025-01-03,2402.58,2454.67,2402.58,2441.92,407536387,0.0179,1,42.98,8230070287923,1998126924797077
2025-01-06,2453.30,2489.10,2446.82,2488.64,302760981,0.0191,1,46.72,8142307849602,2036394312458755
2025-01-07,2513.49,2521.86,2492.09,2492.10,407692929,0.0014,1,3.46,9405964049041,2038522932687508
2025-01-08,2481.25,2526.77,2481.25,2521.05,362908922,0.0116,1,28.95,10391057773317,2062626681696110
...,...,...,...,...,...,...,...,...,...,...
2025-06-23,2992.20,3019.81,2971.36,3014.47,625650915,-0.0024,2,-7.37,17879769854238,2465283335804106
2025-06-24,3061.14,3105.04,3061.14,3103.64,579200567,0.0296,1,89.17,19107339943731,2538235150827130
2025-06-25,3127.79,3129.09,3084.86,3108.25,644761399,0.0015,1,4.61,19662628183278,2543092930441839
2025-06-26,3108.34,3113.03,3036.55,3079.56,460611798,-0.0092,2,-28.69,17030574191361,2519593951599544
2025-06-27,3077.87,3093.56,3041.85,3055.94,381633939,-0.0077,2,-23.62,13970283384996,2500663765269373

In [13]:
DJI_idx_data = fdr.DataReader("DJI", "2025-01-01", "2025-06-27")
display(DJI_idx_data)

,Open,High,Low,Close,Volume,Adj Close
2024-12-31,42636.699219,42779.691406,42421.289062,42544.218750,359210000,42544.218750
2025-01-02,42660.089844,42905.089844,42174.800781,42392.269531,459850000,42392.269531
2025-01-03,42495.761719,42782.761719,42436.921875,42732.128906,455810000,42732.128906
2025-01-06,42835.519531,43115.308594,42611.160156,42706.558594,557040000,42706.558594
2025-01-07,42809.710938,42931.539062,42380.750000,42528.359375,621630000,42528.359375
...,...,...,...,...,...,...
2025-06-20,42291.089844,42432.191406,42089.988281,42206.820312,859840000,42206.820312
2025-06-23,42178.550781,42609.468750,41981.140625,42581.781250,496750000,42581.781250
2025-06-24,42807.128906,43183.480469,42794.078125,43089.019531,516060000,43089.019531
2025-06-25,43130.328125,43130.328125,42871.500000,42982.429688,527460000,42982.429688
2025-06-26,43084.070312,43430.988281,43084.070312,43386.839844,536710000,43386.839844

# [프로젝트] 코스피와 코스닥 전종목 주가 데이터 수집하기

In [14]:
import FinanceDataReader as fdr

In [34]:
# 종목 목록 가져오기
stock_list = fdr.StockListing("KRX")
display(stock_list)

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,60800,1,600,1.00,60100,61600,60000,17340470,1053939281525,359913985657600,5919637922,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,284000,2,-9000,-3.07,288000,294500,281000,5134863,1469227568381,206752671660000,728002365,STK
2,207940,KR7207940008,삼성바이오로직스,KOSPI,,996000,2,-3000,-0.30,1004000,1005000,993000,38057,37915832500,70889304000000,71174000,STK
3,373220,KR7373220003,LG에너지솔루션,KOSPI,,288000,2,-9000,-3.03,297500,297500,287000,219699,63656967000,67392000000000,234000000,STK
4,105560,KR7105560007,KB금융,KOSPI,,110600,1,700,0.64,110000,112300,109500,1045704,115861647400,42189708591800,381462103,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1300,1,3,0.23,1300,1300,1103,12,13630,2053948000,1579960,KNX
2871,288490,KR7288490006,나라소프트,KONEX,일반기업부,105,0,0,0.00,0,0,0,0,0,1834515585,17471577,KNX
2872,236030,KR7236030003,씨알푸드,KONEX,일반기업부,899,3,0,0.00,899,899,899,3,2697,1827965468,2033332,KNX
2873,308700,KR7308700004,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,0,0,0,1472600000,7400000,KNX
2874,217320,KR7217320001,썬테크,KONEX,일반기업부,1090,0,0,0.00,0,0,0,0,0,1144500000,1050000,KNX

In [16]:
#코넥스 종목 제외
stock_list = stock_list.loc[stock_list["Market"] != "KONEX"]

In [22]:
print(stock_list.columns)

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [27]:
# 종목 정보 내보내기
import os

save_dir = "../../데이터"
os.makedirs(save_dir, exist_ok = True)
save_path = os.path.join(save_dir, "종목정보.txt")
stock_list.to_csv(save_path, sep = "\t", index = False , encoding = "euc-kr")

In [ ]:
import time
for code, name in stock_list[['Code' , "Name"]].values:
    print(code, name)
    while True:
        try:
            data = fdr.DataReader (code, "2025-01-01", "2025-06-27")
            if len(data) > 300:
                data.to_csv("../../데이터/주가데이터/{}.csv".format(name))
            time.sleep(1)
            break
        except:
            time.sleep( 10 * 60)

005930 삼성전자
000660 SK하이닉스
207940 삼성바이오로직스
373220 LG에너지솔루션
105560 KB금융
034020 두산에너빌리티
012450 한화에어로스페이스
005380 현대차
005935 삼성전자우
035420 NAVER
000270 기아
329180 HD현대중공업
068270 셀트리온
055550 신한지주
028260 삼성물산
035720 카카오
012330 현대모비스
009540 HD한국조선해양
032830 삼성생명
015760 한국전력
042660 한화오션
086790 하나금융지주
402340 SK스퀘어
011200 HMM
064350 현대로템
005490 POSCO홀딩스
196170 알테오젠
138040 메리츠금융지주
000810 삼성화재
267260 HD현대일렉트릭
010130 고려아연
259960 크래프톤
316140 우리금융지주
033780 KT&G
323410 카카오뱅크
096770 SK이노베이션
051910 LG화학
024110 기업은행
034730 SK
010140 삼성중공업
030200 KT
006400 삼성SDI
018260 삼성에스디에스
352820 하이브
003550 LG
006800 미래에셋증권
066570 LG전자
017670 SK텔레콤
079550 LIG넥스원
377300 카카오페이
272210 한화시스템
000150 두산
086280 현대글로비스
009150 삼성전기
003230 삼양식품
267250 HD현대
042700 한미반도체
247540 에코프로비엠
003670 포스코퓨처엠
443060 HD현대마린솔루션
047810 한국항공우주
000720 현대건설
005830 DB손해보험
003490 대한항공
010120 LS ELECTRIC
047050 포스코인터내셔널
000100 유한양행
064400 LG씨엔에스
298040 효성중공업
010620 HD현대미포
180640 한진칼
071050 한국금융지주
090430 아모레퍼시픽
326030 SK바이오팜
000880 한화
021240 코웨이
016360 삼성증권
010950 S-Oil
005940 NH투자증권
028300 HLB
032640 LG유플러스
086520 에코프로
006260 LS
029780 삼성카드
039490 키움증권
009830 한화솔루션
278470 에이피알
241560 두산밥캣
005387 현대차2우B
088980 맥쿼리인프라
277810 레인보우로보틱스
307950 현대오토에버
214450 파마리서치
251270 넷마블
051900 LG생활건강
161390 한국타이어앤테크놀로지
087010 펩트론
001040 CJ
034220 LG디스플레이
145020 휴젤
028050 삼성E&A
454910 두산로보틱스
141080 리가켐바이오
078930 GS
011790 SKC
271560 오리온
214150 클래시스
004020 현대제철
052690 한전기술
036570 엔씨소프트
175330 JB금융지주
138930 BNK금융지주
035250 강원랜드
058470 리노공업
103140 풍산
302440 SK바이오사이언스
097950 CJ제일제당
128940 한미약품
007660 이수페타시스
036460 한국가스공사
005385 현대차우
022100 포스코DX
000250 삼천당제약
011070 LG이노텍
257720 실리콘투
950160 코오롱티슈진
017800 현대엘리베이터
298380 에이비엘바이오
450080 에코프로머티
041510 에스엠
192820 코스맥스
001440 대한전선
008930 한미사이언스
383220 F&F
031210 서울보증보험
011780 금호석유화학
004990 롯데지주
088350 한화생명
462870 시프트업
111770 영원무역
026960 동서
002380 KCC
051600 한전KPS
263750 펄어비스
082270 젬백스
035900 JYP Ent.
012750 에스원
489790 한화비전
062040 산일전기
011170 롯데케미칼
002790 아모레퍼시픽홀딩스
042670 HD현대인프라코어
403870 HPSP
004370 농심
001450 현대해상
139480 이마트
030000 제일기획
082740 한화엔진
018670 SK가스
483650 달바글로벌
161890 한국콜마
068760 셀트리온제약
310210 보로노이
018880 한온시스템
375500 DL이앤씨
081660 미스토홀딩스
023530 롯데쇼핑
139130 iM금융지주
039030 이오테크닉스
282330 BGF리테일
000990 DB하이텍
008770 호텔신라
112610 씨에스윈드
003690 코리안리
065350 신성델타테크
000120 CJ대한통운
020560 아시아나항공
028670 팬오션
140860 파크시스템스
012510 더존비즈온
001720 신영증권
361610 SK아이이테크놀로지
014680 한솔케미칼
007390 네이처셀
006360 GS건설
004170 신세계
009970 영원무역홀딩스
006040 동원산업
003570 SNT다이내믹스
066970 엘앤에프
103590 일진전기
000240 한국앤컴퍼니
047040 대우건설
214370 케어젠
096530 씨젠
122870 와이지엔터테인먼트
069960 현대백화점
071970 HD현대마린엔진
293490 카카오게임즈
005290 동진쎄미켐
069620 대웅제약
035760 CJ ENM
294870 HDC현대산업개발
000155 두산우
007310 오뚜기
253450 스튜디오드래곤
328130 루닛
237690 에스티팜
023590 다우기술
204320 HL만도
036930 주성엔지니어링
336260 두산퓨얼셀
376300 디어유
006280 녹십자
005850 에스엘
484870 엠앤씨솔루션
003530 한화투자증권
000080 하이트진로
007070 GS리테일
357780 솔브레인
034230 파라다이스
010060 OCI홀딩스
003090 대웅
001800 오리온홀딩스
358570 지아이이노베이션
267270 HD현대건설기계
012630 HDC
005440 현대지에프홀딩스
347850 디앤디파마텍
457190 이수스페셜티케미컬
017960 한국카본
032350 롯데관광개발
395400 SK리츠
007340 DN오토모티브
240810 원익IPS
073240 금호타이어
137310 에스디바이오센서
009420 한올바이오파마
300720 한일시멘트
083650 비에이치아이
095340 ISC
011210 현대위아
089860 롯데렌탈
004800 효성
120110 코오롱인더
003540 대신증권
003240 태광산업
018290 브이티
089030 테크윙
064760 티씨케이
192080 더블유게임즈
348370 엔켐
285130 SK케미칼
001120 LX인터내셔널
112040 위메이드
195940 HK이노엔
178320 서진시스템
086900 메디톡스
160190 하이젠알앤엠
042000 카페24
020150 롯데에너지머티리얼즈
140410 메지온
00680K 미래에셋증권2우B
039200 오스코텍
185750 종근당
001430 세아베스틸지주
098460 고영
085620 미래에셋생명
100090 SK오션플랜트
204270 제이앤티씨
005300 롯데칠성
330590 롯데리츠
005070 코스모신소재
082640 동양생명
009450 경동나비엔
192400 쿠쿠홀딩스
108320 LX세미콘
078600 대주전자재료
298020 효성티앤씨
280360 롯데웰푸드
009240 한샘
000500 가온전선
006120 SK디스커버리
067160 SOOP
229640 LS에코에너지
060370 LS마린솔루션
004000 롯데정밀화학
003380 하림지주
181710 NHN
000815 삼성화재우
415640 KB발해인프라
030190 NICE평가정보
336570 원텍
001740 SK네트웍스
030610 교보증권
071320 지역난방공사
004490 세방전지
388720 유일로보틱스
000210 DL
108490 로보티즈
225570 넥슨게임즈
025980 아난티
114090 GKL
298050 HS효성첨단소재
052400 코나아이
365550 ESR켄달스퀘어리츠
014820 동원시스템즈
078130 국일제지
036530 SNT홀딩스
084370 유진테크
161580 필옵틱스
077970 STX엔진
213420 덕산네오룩스
007700 F&F홀딩스
003030 세아제강지주
353200 대덕전자
009410 태영건설
085660 차바이오텍
056190 에스에프에이
101490 에스앤에스텍
039130 하나투어
036830 솔브레인홀딩스
100840 SNT에너지
079900 전진건설로봇
232140 와이씨
475150 SK이터닉스
064960 SNT모티브
079160 CJ CGV
000670 영풍
281740 레이크머티리얼즈
067310 하나마이크론
051915 LG화학우
214320 이노션
005690 파미셀
419530 SAMG엔터
005180 빙그레
002840 미원상사
323280 태성
001530 DI동일
049770 동원F&B
183300 코미코
014620 성광벤드
033500 동성화인텍
086450 동국제약
00088K 한화3우B
053800 안랩
417200 LS머트리얼즈
031980 피에스케이홀딩스
005250 녹십자홀딩스
001680 대상
000070 삼양홀딩스
222800 심텍
137400 피엔티
211050 인카금융서비스
041190 우리기술투자
030520 한글과컴퓨터
003470 유안타증권
032820 우리기술
218410 RFHIC
381970 케이카
000640 동아쏘시오홀딩스
248070 솔루엠
335890 비올
451800 한화리츠
268280 미원에스씨
499790 GS피앤엘
226950 올릭스
950210 프레스티지바이오파마
251970 펌텍코리아
383800 LX홀딩스
003620 KG모빌리티
214430 아이쓰리시스템
008730 율촌화학
003850 보령
145720 덴티움
101730 위메이드맥스
044490 태웅
290650 엘앤씨바이오
019170 신풍제약
293940 신한알파리츠
057050 현대홈쇼핑
069260 TKG휴켐스
002020 코오롱
000370 한화손해보험
058970 엠로
025540 한국단자
097230 HJ중공업
033100 제룡전기
005810 풍산홀딩스
032190 다우데이타
460930 현대힘스
010780 아이에스동서
075580 세진중공업
002030 아세아
082920 비츠로셀
025320 시노펙스
001570 금양
066575 LG전자우
445680 큐리옥스바이오시스템즈
440110 파두
200670 휴메딕스
241710 코스메카코리아
006380 카프로
319400 현대무벡스
058610 에스피지
016380 KG스틸
024720 콜마홀딩스
067630 HLB생명과학
002350 넥센타이어
121600 나노신소재
014830 유니드
005390 신성통상
287840 인투셀
271940 일진하이솔루스
006730 서부T&D
006220 제주은행
336370 솔루스첨단소재
036620 감성코퍼레이션
084110 휴온스글로벌
089590 제주항공
124500 아이티센글로벌
453340 현대그린푸드
005420 코스모화학
304100 솔트룩스
284740 쿠쿠홈시스
319660 피에스케이
281820 케이씨텍
047920 HLB제약
000400 롯데손해보험
00104K CJ4우(전환)
119850 지엔씨에너지
003300 한일홀딩스
080220 제주반도체
102710 이엔에프테크놀로지
215200 메가스터디교육
002960 한국쉘석유
131970 두산테스나
095660 네오위즈
189300 인텔리안테크
006650 대한유화
222080 씨아이에스
037270 YG PLUS
017940 E1
071055 한국금융지주우
344820 KCC글라스
348210 넥스틴
036540 SFA반도체
004690 삼천리
399720 가온칩스
099320 쎄트렉아이
145990 삼양사
078340 컴투스
003545 대신증권우
029530 신도리코
001060 JW중외제약
005880 대한해운
093050 LF
166090 하나머티리얼즈
383310 에코프로에이치엔
377740 바이오노트
161000 애경케미칼
023160 태광
348950 제이알글로벌리츠
016590 신대양제지
093370 후성
178920 PI첨단소재
095610 테스
194480 데브시스터즈
016800 퍼시스
053030 바이넥스
456040 OCI
069080 웹젠
032500 케이엠더블유
322000 HD현대에너지솔루션
466100 클로봇
097520 엠씨넥스
099190 아이센스
001500 현대차증권
094480 갤럭시아머니트리
002240 고려제강
272450 진에어
093320 케이아이엔엑스
195870 해성디에스
034120 SBS
389260 대명에너지
009520 포스코엠텍
005610 SPC삼립
074600 원익QnC
204620 글로벌텍스프리
130660 한전산업
340570 티앤엘
460860 동국제강
015750 성우하이텍
052020 에스티큐브
272290 이녹스첨단소재
034310 NICE
078160 메디포스트
183190 아세아시멘트
090435 아모레퍼시픽우
402030 코난테크놀로지
017810 풀무원
241590 화승엔터프라이즈
059090 미코
026890 스틱인베스트먼트
031430 신세계인터내셔날
206650 유바이오로직스
060250 NHN KCP
034950 한국기업평가
372320 큐로셀
003160 디아이
017860 DS단석
050890 쏠리드
314930 바이오다인
450950 아스테라시스
437730 삼현
170900 동아에스티
131290 티에스이
091810 티웨이항공
347700 스피어
009900 명신산업
403550 쏘카
357120 코람코라이프인프라리츠
056080 유진로봇
448280 에코아이
102940 코오롱생명과학
090460 비에이치
058650 세아홀딩스
001270 부국증권
025900 동화기업
064260 다날
003280 흥아해운
200130 콜마비앤에이치
048410 현대바이오
002710 TCC스틸
115180 큐리언트
215000 골프존
306200 세아제강
018250 애경산업
105630 한세실업
179900 유티아이
099430 바이오플러스
030530 원익홀딩스
108860 셀바스AI
192650 드림텍
046890 서울반도체
253590 네오셈
004700 조광피혁
215600 신라젠
475560 더본코리아
079370 제우스
448730 삼성FN리츠
003520 영진약품
115450 HLB테라퓨틱스
094800 맵스리얼티1
365340 성일하이텍
217270 넵튠
036810 에프에스티
027410 BGF
475830 오름테라퓨틱
060280 큐렉소
278280 천보
432320 KB스타리츠
140610 엔솔바이오사이언스
035890 서희건설
260970 에스앤디
003920 남양유업
041960 코미팜
900140 엘브이엠씨홀딩스
389650 넥스트바이오메디컬
000157 두산2우B
025860 남해화학
126720 수산인더스트리
397030 에이프릴바이오
060980 HL홀딩스
098070 한텍
011760 현대코퍼레이션
064550 바이오니아
025770 한국정보통신
020000 한섬
084010 대한제강
084690 대상홀딩스
003960 사조대림
472850 폰드그룹
072710 농심홀딩스
013890 지누스
094170 동운아나텍
045390 대아티아이
455900 엔젤로보틱스
256940 킵스파마
100790 미래에셋벤처투자
203400 에이비온
091700 파트론
006390 한일현대시멘트
101930 인화정공
005389 현대차3우B
013030 하이록코리아
101360 에코앤드림
094360 칩스앤미디어
126560 현대퓨처넷
389470 인벤티지랩
083450 GST
286940 롯데이노베이트
424870 이뮨온시아
101160 월덱스
089010 켐트로닉스
079940 가비아
295310 에이치브이엠
445090 에이직랜드
093230 이아이디
005090 SGC에너지
256840 한국비엔씨
249420 일동제약
001940 KISCO홀딩스
016610 DB증권
001200 유진투자증권
053300 한국정보인증
092790 넥스틸
090710 휴림로봇
122640 예스티
194700 노바렉스
065680 우주일렉트로
038500 삼표시멘트
068240 다원시스
452450 피아이이
005945 NH투자증권우
220100 퓨쳐켐
950170 JTC
002310 아세아제지
033240 자화전자
005720 넥센
475960 토모큐브
420770 기가비스
033270 유나이티드제약
206640 바디텍메드
473980 노머스
104700 한국철강
194370 제이에스코퍼레이션
243070 휴온스
200880 서연이화
015360 INVENI
001510 SK증권
003800 에이스침대
082800 비보존 제약
144510 지씨셀
352480 씨앤씨인터내셔널
457550 우진엔텍
009160 SIMPAC
043150 바텍
462860 더즌
041830 인바디
045100 한양이엔지
171090 선익시스템
136480 하림
425420 티에프이
317330 덕산테코피아
007690 국도화학
018310 삼목에스폼
041020 폴라리스오피스
394280 오픈엣지테크놀로지
035150 백산
001390 KG케미칼
000320 노루홀딩스
029460 케이씨
034830 한국토지신탁
051500 CJ프레시웨이
123890 한국자산신탁
039440 에스티아이
054950 제이브이엠
168360 펨트론
000680 LS네트웍스
123330 제닉
114840 아이패밀리에스씨
009290 광동제약
011930 신성이엔지
007160 사조산업
089970 브이엠
439090 마녀공장
003120 일성아이에스
458870 씨어스테크놀로지
027360 아주IB투자
089980 상아프론테크
002320 한진
035600 KG이니시스
267980 매일유업
003220 대원제약
252990 샘씨엔에스
004430 송원산업
338220 뷰노
010690 화신
031330 에스에이엠티
228760 지노믹트리
176750 듀켐바이오
237880 클리오
481070 에이유브랜즈
298830 슈어소프트테크
002810 삼영무역
090360 로보스타
475400 씨메스
138610 나이벡
012030 DB
017390 서울가스
009680 모토닉
377450 리파인
151860 KG에코솔루션
058820 CMG제약
018000 유니슨
049070 인탑스
004360 세방
226320 잇츠한불
092230 KPX홀딩스
230360 에코마케팅
088260 이리츠코크렙
348340 뉴로메카
084850 아이티엠반도체
104830 원익머트리얼즈
416180 신성에스티
378340 필에너지
377190 디앤디플랫폼리츠
108670 LX하우시스
000490 대동
051905 LG생활건강우
136490 선진
035510 신세계 I&C
036220 오상헬스케어
001820 삼화콘덴서
122900 아이마켓코리아
078020 LS증권
489460 바이오비쥬
023410 유진기업
294570 쿠콘
127120 제이에스링크
033640 네패스
000540 흥국화재
053610 프로텍
047560 이스트소프트
357550 석경에이티
039840 디오
067080 대화제약
214420 토니모리
114810 한솔아이원스
461300 아이스크림미디어
007570 일양약품
334970 프레스티지바이오로직스
008060 대덕
418550 제이오
459510 나우로보틱스
265520 AP시스템
007810 코리아써키트
105550 엣지파운드리
005500 삼진제약
339770 교촌에프앤비
487570 HS효성
254490 미래반도체
389020 자람테크놀로지
006110 삼아알미늄
001340 PKC
024850 HLB이노베이션
112290 와이씨켐
005010 휴스틸
136150 원일티엔아이
121800 비덴트
001790 대한제당
096760 JW홀딩스
034810 해성산업
199800 툴젠
060150 인선이엔티
000480 CR홀딩스
240550 동방메디컬
006060 화승인더
298690 에어부산
015860 일진홀딩스
001630 종근당홀딩스
182360 큐브엔터
093520 매커스
138490 코오롱ENP
035810 이지홀딩스
158430 아톤
001130 대한제분
001230 동국홀딩스
230240 에치에프알
150840 인트로메딕
042370 비츠로테크
014940 오리엔탈정공
003200 일신방직
441270 파인엠텍
003350 한국화장품제조
036030 케이티알파
048870 시너지이노베이션
060720 KH바텍
205500 넥써쓰
095500 미래나노텍
003000 부광약품
236200 슈프리마
334890 이지스밸류플러스리츠
393890 더블유씨피
304360 에스바이오메딕스
179290 엠아이텍
377030 비트맥스
013120 동원개발
484810 티엑스알로보틱스
452260 한화갤러리아
036890 진성티이씨
096040 이트론
051360 토비스
308430 셀비온
267320 나인테크
900290 GRT
356680 엑스게이트
464080 에스오에스랩
110990 디아이티
001460 BYC
376900 로킷헬스케어
037710 광주신세계
000140 하이트진로홀딩스
039570 HDC랩스
121440 골프존홀딩스
042420 네오위즈홀딩스
053210 스카이라이프
002900 TYM
086390 유니테스트
070960 모나용평
476040 오가노이드사이언스
053580 웹케시
011500 한농화성
476060 온코닉테라퓨틱스
208340 파멥신
036420 콘텐트리중앙
290690 소룩스
117730 티로보틱스
058430 포스코스틸리온
234340 헥토파이낸셜
084680 이월드
007860 서연
025000 KPX케미칼
105840 우진
117580 대성에너지
043370 피에이치에이
000430 대원강업
323990 박셀바이오
080160 모두투어
260870 SK시그넷
200710 에이디테크놀로지
950140 잉글우드랩
023760 한국캐피탈
394800 쓰리빌리언
016880 웅진
107640 한중엔시에스
004980 성신양회
067390 아스트
053690 한미글로벌
271980 제일약품
452430 사피엔반도체
372170 윤성에프앤씨
006340 대원전선
001750 한양증권
102460 이연제약
016580 환인제약
371950 풍원정밀
002150 도화엔지니어링
005680 삼영전자
456010 아이씨티케이
255220 SG
092730 네오팜
126700 하이비젼시스템

In [30]:
display(stock_list)
print(stock_list.columns)

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,60800,1,600,1.00,60100,61600,60000,17340470,1053939281525,359913985657600,5919637922,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,284000,2,-9000,-3.07,288000,294500,281000,5134863,1469227568381,206752671660000,728002365,STK
2,207940,KR7207940008,삼성바이오로직스,KOSPI,,996000,2,-3000,-0.30,1004000,1005000,993000,38057,37915832500,70889304000000,71174000,STK
3,373220,KR7373220003,LG에너지솔루션,KOSPI,,288000,2,-9000,-3.03,297500,297500,287000,219699,63656967000,67392000000000,234000000,STK
4,105560,KR7105560007,KB금융,KOSPI,,110600,1,700,0.64,110000,112300,109500,1045704,115861647400,42189708591800,381462103,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2861,001527,KR7001522002,동양2우B,KOSPI,,8630,1,210,2.49,8500,8630,8500,91,774960,2662950470,308569,STK
2862,032685,KR7032681009,소프트센우,KOSDAQ,중견기업부,7380,1,160,2.22,7230,7400,7230,468,3395610,2635707960,357142,KSQ
2863,001525,KR7001521004,동양우,KOSPI,,4230,1,125,3.05,4200,4230,4200,1114,4684830,2613002130,617731,STK
2866,021045,KR7021041009,대호특수강우,KOSDAQ,중견기업부,2760,2,-35,-1.25,2735,2760,2735,3338,9142675,2341837920,848492,KSQ
2867,002787,KR7002782001,진흥기업2우B,KOSPI,,7900,1,10,0.13,8010,8010,7870,7945,62685510,2328983200,294808,STK

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

# OpenDart를 이용한 기업공시 수집

In [1]:
!pip install opendartreader

Collecting opendartreader
  Downloading OpenDartReader-0.2.3-py3-none-any.whl.metadata (913 bytes)
Requirement already satisfied: pandas>=0.19.2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from opendartreader) (2.2.3)
Requirement already satisfied: requests>=2.3.0 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from opendartreader) (2.32.3)
Requirement already satisfied: requests-file in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from opendartreader) (2.1.0)
Requirement already satisfied: lxml in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from opendartreader) (6.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from opendartreader) (4.12.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.19.2->opendartreader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.19.2->opendartreader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.19.2->opendartreader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.19.2->opendartreader) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->opendartreader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->opendartreader) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->opendartreader) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from requests>=2.3.0->opendartreader) (2025.1.31)
Requirement already satisfied: soupsieve>1.2 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from beautifulsoup4->opendartreader) (2.5)
Requirement already satisfied: six>=1.5 in c:\users\yms10\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.19.2->opendartreader) (1.17.0)
Downloading OpenDartReader-0.2.3-py3-none-any.whl (27 kB)
Installing collected packages: opendartreader
Successfully installed opendartreader-0.2.3

In [ ]:
import OpenDartReader

In [6]:
my_api = "2502ce016b74cab3d09e7e74d5d1f31e098ff954"
dart = OpenDartReader(my_api) #opendartreader 객체 생성

In [10]:
result = dart.list( corp = "005930" , start = "2024-01-01", end = "2024-12-31")
display(result.head()) #위 5개 행 출력
display(result.shape)

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20241223000116,김상하,20241223,
1,00126380,삼성전자,005930,Y,[기재정정]기타경영사항(자율공시),20241223800004,삼성전자,20241223,유
2,00126380,삼성전자,005930,Y,주식등의대량보유상황보고서(일반),20241220000709,삼성물산,20241220,
3,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20241219000121,홍준화,20241219,
4,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20241217000409,송기재,20241217,

(265, 9)

In [7]:
corp_list = dart.corp_codes  # 전체 상장법인 리스트 가져오기
print(len(corp_list))

112777

In [12]:
doc = dart.document("20241223000116")
print(doc)

<?xml version="1.0" encoding="utf-8"?>


<DOCUMENT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dart4.xsd">

<DOCUMENT-NAME ACODE="00634">임원ㆍ주요주주 특정증권등 소유상황보고서</DOCUMENT-NAME>
<FORMULA-VERSION ADATE="20231229">4.1</FORMULA-VERSION>
<COMPANY-NAME AREGCIK="00126380">삼성전자주식회사</COMPANY-NAME>

<SUMMARY>
<EXTRACTION ACODE="OUTDATE" AFEATURE="BOTH">20241129</EXTRACTION>
</SUMMARY>


<BODY ATOCID="7">

<COVER>
<P></P>
<COVER-TITLE ATOC="Y" AASSOCNOTE="COVER" ATOCID="1">임원ㆍ주요주주 특정증권등 소유상황보고서</COVER-TITLE>
<P></P>

<TABLE-GROUP ACLASS="RPT_RSP_DT" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="600" BORDER="0">

<COLGROUP WIDTH="600">
<COL WIDTH="260"></COL>
<COL WIDTH="163"></COL>
<COL WIDTH="177"></COL>
</COLGROUP>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD WIDTH="251" HEIGHT="23">증권선물위원회 귀중</TD>
<TD WIDTH="154" HEIGHT="23"></TD>
<TD ALIGN="CENTER" WIDTH="168" HEIGHT="23"></TD>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD WIDTH="251" HEIGHT="23">한국거래소 귀중</TD>
<TD WIDTH="154" HEIGHT="23"></TD>
<TD ALIGN="CENTER" WIDTH="168" HEIGHT="23"></TD>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ROWSPAN="2" WIDTH="251" HEIGHT="53"></TD>
<TD WIDTH="154" HEIGHT="23" AUPDATECONT="N">보고의무발생일   :</TD>
<TU ALIGN="CENTER" WIDTH="168" HEIGHT="23" AUNIT="RPT_RSP_DT" AUNITVALUE="20241220">2024.12.20</TU>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD WIDTH="154" HEIGHT="23" AUPDATECONT="N">보고서작성기준일 : </TD>
<TU ALIGN="CENTER" WIDTH="168" HEIGHT="23" AUNIT="RPT_REF_DT" AUNITVALUE="20241220">2024.12.20</TU>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>
<P></P>

<TABLE ACLASS="NORMAL" AFIXTABLE="Y" WIDTH="600" BORDER="1">

<COLGROUP WIDTH="600">
<COL WIDTH="600"></COL>
</COLGROUP>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="76">
<TD WIDTH="591" HEIGHT="69" AUPDATECONT="N">※ 보고자 본인은 보고서작성기준일 현재 본인의 특정증권등의 소유상황을 관련 법규 및 기재상의 주의에 따라 정확하게 작성하였고, 중요한 사항의 허위기재 또는 기재누락이 없음을 확인합니다.</TD>
</TR>
</TBODY>
</TABLE>
<P></P>

<TABLE ACLASS="NORMAL" AFIXTABLE="N" WIDTH="600" BORDER="0">

<COLGROUP WIDTH="600">
<COL WIDTH="169"></COL>
<COL WIDTH="431"></COL>
</COLGROUP>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="160" HEIGHT="23">보고자 : 김상하</TD>
<TD VALIGN="MIDDLE" WIDTH="422" HEIGHT="23"></TD>
</TR>
</TBODY>
</TABLE>
<P></P>
<P></P>
<PGBRK></PGBRK>
<P></P>
</COVER>

<LIBRARY>
<SECTION-1 ACLASS="MANDATORY" APARTSOURCE="SOURCE">

<SECTION-2 ACLASS="MANDATORY">
<TITLE ATOC="Y" AASSOCNOTE="D-0-1-1-0" ATOCID="2">1. 발행회사에 관한 사항</TITLE>

<TABLE-GROUP ACLASS="CRP_NM" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="600" BORDER="1">

<COLGROUP WIDTH="600">
<COL WIDTH="150"></COL>
<COL WIDTH="137"></COL>
<COL WIDTH="163"></COL>
<COL WIDTH="150"></COL>
</COLGROUP>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="141" HEIGHT="23" AUPDATECONT="N">회 사 명</TD>
<TE VALIGN="MIDDLE" WIDTH="441" HEIGHT="23" ACODE="CRP_NM" COLSPAN="3">삼성전자주식회사</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="141" HEIGHT="23" AUPDATECONT="N">법인구분</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="128" HEIGHT="23" AUNIT="CRP_DST" AUNITVALUE="1">유가증권상장법인</TU>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="154" HEIGHT="23" AUPDATECONT="N">회사코드 </TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="141" HEIGHT="23" ACODE="CRP_CD">005930</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="141" HEIGHT="23" AUPDATECONT="N">발행주식 총수</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="441" HEIGHT="23" ACODE="FLT_SUM" COLSPAN="3">6,792,669,250</TE>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>
<P></P>
</SECTION-2>

<SECTION-2 ACLASS="MANDATORY">
<TITLE ATOC="Y" AASSOCNOTE="D-0-1-2-0" ATOCID="3">2. 보고자에 관한 사항</TITLE>

<TABLE-GROUP ACLASS="IFR_NM" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="600" BORDER="1">

<COLGROUP WIDTH="600">
<COL WIDTH="133"></COL>
<COL WIDTH="115"></COL>
<COL WIDTH="133"></COL>
<COL WIDTH="83"></COL>
<COL WIDTH="136"></COL>
</COLGROUP>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" AUPDATECONT="N">보고구분</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUNIT="RPT_DST" AUNITVALUE="1">신규</TU>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" AUPDATECONT="N">보고자 구분</TD>
<TU COLSPAN="2" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="210" HEIGHT="23" AUNIT="IFR_TP" AUNITVALUE="D">개인(국내)</TU>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="53">
<TD ROWSPAN="2" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="76" AUPDATECONT="N">성명(명칭)</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="46" AUPDATECONT="N">한     글</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="46" ACODE="IFR_NM">김상하</TE>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="46" AUPDATECONT="N">한자(영문)</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="46" ACODE="IFR_NM_HJ">金想荷(Kim Sang Ha)</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD COLSPAN="2" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="239" HEIGHT="23" AUPDATECONT="N">생년월일 또는 사업자등록번호 등</TD>
<TE COLSPAN="2" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="210" HEIGHT="23" ACODE="IFR_ID2">810120</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="76">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="69" AUPDATECONT="N">주소(본점소재지)[읍ㆍ면ㆍ동까지만 기재]</TD>
<TE COLSPAN="4" VALIGN="MIDDLE" WIDTH="458" HEIGHT="69" ACODE="IFR_ADR2">서울시 송파구 올림픽로</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ROWSPAN="3" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="83" AUPDATECONT="N">발행회사와의 관계</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">임원(등기여부)</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" AUNIT="STF_RYN" AUNITVALUE="N">비등기임원</TU>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="23" AUPDATECONT="N">직위명</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="23" ACODE="STF_PSM">상무</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">선임일</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" AUNIT="STF_APT_DT" AUNITVALUE="20241129">2024.11.29</TU>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="23" AUPDATECONT="N">퇴임일</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="23" AUNIT="STF_RET_DT" AUNITVALUE="-">-</TU>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">주요주주</TD>
<TU COLSPAN="3" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="343" HEIGHT="23" AUNIT="MAIN_SH" AUNITVALUE="4">-</TU>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="53">
<TD ROWSPAN="4" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="136" AUPDATECONT="N">업무상 연락처및 담당자</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="46" AUPDATECONT="N">소속회사</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="46" ACODE="RSP_MAN_DPT">삼성전자주식회사</TE>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="46" AUPDATECONT="N">부      서</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="46" ACODE="RSP_MAN_DPT2">AI Productivity팀</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">직      위</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" ACODE="RSP_MAN_PST">상무</TE>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="23" AUPDATECONT="N">전화번호</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="23" ACODE="RSP_MAN_PHN2">010 30*******</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">성      명</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" ACODE="RSP_MAN">김상하</TE>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="74" HEIGHT="23" AUPDATECONT="N">팩스번호</TD>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="127" HEIGHT="23" ACODE="RSP_MAN_FAX">031-27******</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="23" AUPDATECONT="N">이메일 주소</TD>
<TE COLSPAN="3" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="343" HEIGHT="23" ACODE="RSP_MAN_EML">******01.kim@samsung.com</TE>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>

<P></P>
</SECTION-2>

<SECTION-2 ACLASS="MANDATORY">
<TITLE ATOC="Y" ATOCID="4">3. 특정증권등의 소유상황</TITLE>

<SECTION-3 ACLASS="MANDATORY">
<TITLE ATOC="Y" AASSOCNOTE="D-0-1-3-1" ATOCID="5">가. 소유 특정증권등의 수 및 소유비율</TITLE>

<TABLE-GROUP ACLASS="BFR_PS_CNT" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="590" BORDER="1">

<COLGROUP WIDTH="590">
<COL WIDTH="90"></COL>
<COL WIDTH="127"></COL>
<COL WIDTH="126"></COL>
<COL WIDTH="70"></COL>
<COL WIDTH="111"></COL>
<COL WIDTH="66"></COL>
</COLGROUP>

<THEAD>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="81" HEIGHT="76" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N"></TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="118" HEIGHT="76" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">보고서작성 기준일</TH>
<TH COLSPAN="2" VALIGN="MIDDLE" WIDTH="187" HEIGHT="23" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">특정증권등</TH>
<TH COLSPAN="2" VALIGN="MIDDLE" WIDTH="168" HEIGHT="23" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">주권</TH>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="53">
<TH VALIGN="MIDDLE" WIDTH="117" HEIGHT="46" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">특정증권등의수(주)</TH>
<TH VALIGN="MIDDLE" WIDTH="61" HEIGHT="46" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">비율(%)</TH>
<TH VALIGN="MIDDLE" WIDTH="102" HEIGHT="46" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">주식수(주)</TH>
<TH VALIGN="MIDDLE" WIDTH="57" HEIGHT="46" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">비율(%)</TH>
</TR>
</THEAD>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="81" HEIGHT="23" AUPDATECONT="N">직전보고서</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="118" HEIGHT="23" AUNIT="BFR_RPT_DT" AUNITVALUE="-">-</TU>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="117" HEIGHT="23" ACODE="BFR_UN_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="61" HEIGHT="23" ACODE="BFR_UN_RT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="102" HEIGHT="23" ACODE="BFR_PS_CPT_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="57" HEIGHT="23" ACODE="BFR_PS_CPT_RT">-</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="81" HEIGHT="23" AUPDATECONT="N">이번보고서</TD>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="118" HEIGHT="23" AUNIT="AFR_RPT_DT" AUNITVALUE="20241129">2024.11.29</TU>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="117" HEIGHT="23" ACODE="AFR_UN_CNT">169</TE>

<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="61" HEIGHT="23" ACODE="AFR_UN_RT">
<SPAN USERMARK=" 0X000000">0.00</SPAN>
</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="102" HEIGHT="23" ACODE="AFR_PS_CPT_CNT">169</TE>

<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="57" HEIGHT="23" ACODE="AFR_PS_CPT_RT">
<SPAN USERMARK=" 0X000000">0.00</SPAN>
</TE>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TD COLSPAN="2" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="208" HEIGHT="23" AUPDATECONT="N">증     감</TD>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="117" HEIGHT="23" ACODE="MDF_UN_CNT">169</TE>

<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="61" HEIGHT="23" ACODE="MDF_UN_RT">
<SPAN USERMARK=" 0X000000">0.00</SPAN>
</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="102" HEIGHT="23" ACODE="MDF_PS_CPT_CNT">169</TE>

<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="57" HEIGHT="23" ACODE="MDF_PS_CPT_RT">
<SPAN USERMARK=" 0X000000">0.00</SPAN>
</TE>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>
<P></P>
</SECTION-3>

<SECTION-3 ACLASS="MANDATORY">
<TITLE ATOC="Y" AASSOCNOTE="D-0-1-3-2" ATOCID="6">나. 특정증권등의 종류별 소유내역</TITLE>

<TABLE-GROUP ACLASS="CST_CNT1" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="N" WIDTH="714" BORDER="1">

<COLGROUP WIDTH="714">
<COL WIDTH="133"></COL>
<COL WIDTH="75"></COL>
<COL WIDTH="60"></COL>
<COL WIDTH="74"></COL>
<COL WIDTH="86"></COL>
<COL WIDTH="60"></COL>
<COL WIDTH="52"></COL>
<COL WIDTH="44"></COL>
<COL WIDTH="65"></COL>
<COL WIDTH="65"></COL>
</COLGROUP>

<THEAD>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TH COLSPAN="10" VALIGN="MIDDLE" WIDTH="705" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">특정증권등의 내역</TH>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TH VALIGN="MIDDLE" WIDTH="124" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N" ROWSPAN="2">주 권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="66" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">신주인수권이표시된것</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="51" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">전환사채권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="65" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">신주인수권부사채권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="77" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">이익참가부사채권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="51" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">교환사채권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="43" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">증권예탁증권</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="35" HEIGHT="76" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">기타</TH>
<TH COLSPAN="2" VALIGN="MIDDLE" WIDTH="121" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">합 계</TH>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="53">
<TH VALIGN="MIDDLE" WIDTH="56" HEIGHT="46" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">주수(주)</TH>
<TH VALIGN="MIDDLE" WIDTH="56" HEIGHT="46" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">비율(%)</TH>
</TR>
</THEAD>

<TBODY>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="124" HEIGHT="23" ACODE="CPT_CNT">169</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="66" HEIGHT="23" ACODE="ACC_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="51" HEIGHT="23" ACODE="CB_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="65" HEIGHT="23" ACODE="LN_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="77" HEIGHT="23" ACODE="BN_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="51" HEIGHT="23" ACODE="EB_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="43" HEIGHT="23" ACODE="CF_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="35" HEIGHT="23" ACODE="ET_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="56" HEIGHT="23" ACODE="STK_CNT">169</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="56" HEIGHT="23" ACODE="STK_RT">0.00</TE>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="124" HEIGHT="53" AUPDATECONT="N" ROWSPAN="2">A</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="66" HEIGHT="23" AUPDATECONT="N">B</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="51" HEIGHT="23" AUPDATECONT="N">C</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="65" HEIGHT="23" AUPDATECONT="N">D</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="77" HEIGHT="23" AUPDATECONT="N">E</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="51" HEIGHT="23" AUPDATECONT="N">F</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="43" HEIGHT="23" AUPDATECONT="N">G</TD>
<TD ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="35" HEIGHT="23" AUPDATECONT="N">H</TD>
<TD ROWSPAN="2" ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="56" HEIGHT="53" AUPDATECONT="N"></TD>
<TD ROWSPAN="2" ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="56" HEIGHT="53" AUPDATECONT="N"></TD>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TD COLSPAN="7" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="442" HEIGHT="23" AUPDATECONT="N">I</TD>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>
<P></P>

<TABLE-GROUP ACLASS="HLD_RT" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="600" BORDER="1">

<COLGROUP WIDTH="600">
<COL WIDTH="118"></COL>
<COL WIDTH="169"></COL>
<COL WIDTH="165"></COL>
<COL WIDTH="148"></COL>
</COLGROUP>

<THEAD>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="109" HEIGHT="99" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">발행주식 총수(J)</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="160" HEIGHT="99" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">주식외 특정증권등의 수(B+C+D+E+F+G+H=I)</TH>
<TH COLSPAN="2" VALIGN="MIDDLE" WIDTH="304" HEIGHT="23" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">소유비율(%)</TH>
</TR>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="76">
<TH VALIGN="MIDDLE" WIDTH="156" HEIGHT="69" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">특정증권등의 소유비율[A+I / J+I-(F+G+H)※] × 100</TH>
<TH VALIGN="MIDDLE" WIDTH="139" HEIGHT="69" ACOPYCOL="Y" ADELETECOL="Y" AMOVECOL="N" AUPDATECONT="N">주권의 소유비율(A / J) × 100</TH>
</TR>
</THEAD>

<TBODY>

<TR ACOPY="Y" ADELETE="Y" HEIGHT="30">
<TE ALIGN="RIGHT" WIDTH="109" HEIGHT="23" ACODE="VOT_STK_CNT">6,792,669,250</TE>
<TE ALIGN="RIGHT" WIDTH="160" HEIGHT="23" ACODE="HLD_STK_CNT">0</TE>
<TE ALIGN="RIGHT" WIDTH="156" HEIGHT="23" ACODE="HLD_STK_RT">0.00</TE>
<TE ALIGN="RIGHT" WIDTH="139" HEIGHT="23" ACODE="HLD_CMT_RT">0.00</TE>
</TR>
</TBODY>
</TABLE>
</TABLE-GROUP>
<P>※ 교환대상이 주식인 교환사채권 및 기초자산이 주식인 증권예탁증권, 파생결합증권 등에 한하여 분모에서 제외하고 소유비율을 산정</P>
</SECTION-3>

<SECTION-3 ACLASS="MANDATORY">
<TITLE ATOC="Y" AASSOCNOTE="D-0-1-3-3" ATOCID="7">다. 세부변동내역</TITLE>

<TABLE-GROUP ACLASS="RPT_RSN" ADELETETABLE="N">

<TABLE ACLASS="EXTRACTION" AFIXTABLE="N" WIDTH="710" BORDER="1">

<COLGROUP WIDTH="710">
<COL WIDTH="75"></COL>
<COL WIDTH="112"></COL>
<COL WIDTH="115"></COL>
<COL WIDTH="74"></COL>
<COL WIDTH="73"></COL>
<COL WIDTH="73"></COL>
<COL WIDTH="121"></COL>
<COL WIDTH="67"></COL>
</COLGROUP>

<THEAD>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="66" HEIGHT="53" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">보고사유</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="103" HEIGHT="53" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">변동일*</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="106" HEIGHT="53" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">특정증권등의종류</TH>
<TH COLSPAN="3" VALIGN="MIDDLE" WIDTH="211" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">소 유 주 식 수 (주)</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="112" HEIGHT="53" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">취득/처분단가(원)**</TH>
<TH ROWSPAN="2" VALIGN="MIDDLE" WIDTH="58" HEIGHT="53" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">비 고</TH>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TH VALIGN="MIDDLE" WIDTH="65" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">변동전</TH>
<TH VALIGN="MIDDLE" WIDTH="64" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">증감</TH>
<TH VALIGN="MIDDLE" WIDTH="64" HEIGHT="23" ACOPYCOL="N" ADELETECOL="N" AMOVECOL="N" AUPDATECONT="N">변동후</TH>
</TR>
</THEAD>

<TBODY>

<TR ACOPY="Y" ADELETE="N" HEIGHT="53">
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="66" HEIGHT="46" AUNIT="RPT_RSN" AUNITVALUE="31">신규선임(+)</TU>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="103" HEIGHT="46" AUNIT="MDF_DM" AUNITVALUE="20241129">2024.11.29</TU>
<TU ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="106" HEIGHT="46" AUNIT="STR_KND" AUNITVALUE="1">보통주</TU>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="65" HEIGHT="46" ACODE="BFR_STK_CNT">-</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="64" HEIGHT="46" ACODE="MDF_STK_CNT">169</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="64" HEIGHT="46" ACODE="AFR_STK_CNT">169</TE>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="112" HEIGHT="46" ACODE="ACI_AMT2">-</TE>
<TE ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="58" HEIGHT="46" ACODE="RMK">-</TE>
</TR>

<TR ACOPY="N" ADELETE="N" HEIGHT="30">
<TD COLSPAN="3" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="293" HEIGHT="23" AUPDATECONT="N">합  계</TD>
<TE ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="65" HEIGHT="23" ACODE="BFR_STK_SUM">-</TE>

In [13]:
print(dart.company("현대자동차"))

{'status': '000', 'message': '정상', 'corp_code': '00164742', 'corp_name': '현대자동차(주)', 'corp_name_eng': 'HYUNDAI MOTOR CO', 'stock_name': '현대자동차', 'stock_code': '005380', 'ceo_nm': '정의선, 이동석, 무뇨스 바르셀로 호세 안토니오(각자 대표이사)', 'corp_cls': 'Y', 'jurir_no': '1101110085450', 'bizr_no': '1018109147', 'adres': '서울특별시 서초구  헌릉로 12', 'hm_url': 'www.hyundai.com', 'ir_url': '', 'phn_no': '02-3464-1114', 'fax_no': '02-3464-8719', 'induty_code': '30121', 'est_dt': '19671229', 'acc_mt': '12'}

In [14]:
display(dart.report("SK하이닉스", "배당", 2024, "11011")) #report 메서드: 사업 보고서의 정보를 알려줌

,rcept_no,corp_cls,corp_code,corp_name,se,thstrm,frmtrm,lwfr,stlm_dt,stock_knd
0,20250319000665,Y,00164779,SK하이닉스,주당액면가액(원),"5,000","5,000","5,000",2024-12-31,NaN
1,20250319000665,Y,00164779,SK하이닉스,(연결)당기순이익(백만원),"19,788,681","-9,112,428","2,229,560",2024-12-31,NaN
2,20250319000665,Y,00164779,SK하이닉스,(별도)당기순이익(백만원),"17,640,396","-4,836,170","2,790,457",2024-12-31,NaN
3,20250319000665,Y,00164779,SK하이닉스,(연결)주당순이익(원),"28,732","-13,244","3,242",2024-12-31,NaN
4,20250319000665,Y,00164779,SK하이닉스,현금배당금총액(백만원),"1,520,090","825,721","825,181",2024-12-31,NaN
5,20250319000665,Y,00164779,SK하이닉스,주식배당금총액(백만원),-,-,-,2024-12-31,NaN
6,20250319000665,Y,00164779,SK하이닉스,(연결)현금배당성향(%),7.70,-,37.00,2024-12-31,NaN
7,20250319000665,Y,00164779,SK하이닉스,현금배당수익률(%),1.10,0.90,1.50,2024-12-31,보통주
8,20250319000665,Y,00164779,SK하이닉스,현금배당수익률(%),-,-,-,2024-12-31,우선주
9,20250319000665,Y,00164779,SK하이닉스,주식배당수익률(%),-,-,-,2024-12-31,보통주
10,20250319000665,Y,00164779,SK하이닉스,주식배당수익률(%),-,-,-,2024-12-31,우선주
11,20250319000665,Y,00164779,SK하이닉스,주당 현금배당금(원),"2,204","1,200","1,200",2024-12-31,보통주
12,20250319000665,Y,00164779,SK하이닉스,주당 현금배당금(원),-,-,-,2024-12-31,우선주
13,20250319000665,Y,00164779,SK하이닉스,주당 주식배당(주),-,-,-,2024-12-31,보통주
14,20250319000665,Y,00164779,SK하이닉스,주당 주식배당(주),-,-,-,2024-12-31,우선주

In [20]:
result = dart.finstate("LG전자", 2024, "11011")
display(result)

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,...,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord,currency
0,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,유동자산,...,2024.12.31 현재,"33,923,517,000,000",제 22 기,2023.12.31 현재,"30,341,209,000,000",제 21 기,2022.12.31 현재,"27,488,228,000,000",1,KRW
1,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,비유동자산,...,2024.12.31 현재,"31,706,072,000,000",제 22 기,2023.12.31 현재,"29,899,584,000,000",제 21 기,2022.12.31 현재,"27,667,913,000,000",3,KRW
2,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,자산총계,...,2024.12.31 현재,"65,629,589,000,000",제 22 기,2023.12.31 현재,"60,240,793,000,000",제 21 기,2022.12.31 현재,"55,156,141,000,000",5,KRW
3,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,유동부채,...,2024.12.31 현재,"27,307,439,000,000",제 22 기,2023.12.31 현재,"24,160,380,000,000",제 21 기,2022.12.31 현재,"22,332,549,000,000",7,KRW
4,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,비유동부채,...,2024.12.31 현재,"13,110,486,000,000",제 22 기,2023.12.31 현재,"12,581,877,000,000",제 21 기,2022.12.31 현재,"10,331,595,000,000",9,KRW
5,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,부채총계,...,2024.12.31 현재,"40,417,925,000,000",제 22 기,2023.12.31 현재,"36,742,257,000,000",제 21 기,2022.12.31 현재,"32,664,144,000,000",11,KRW
6,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,자본금,...,2024.12.31 현재,"904,169,000,000",제 22 기,2023.12.31 현재,"904,169,000,000",제 21 기,2022.12.31 현재,"904,169,000,000",13,KRW
7,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,이익잉여금,...,2024.12.31 현재,"16,352,773,000,000",제 22 기,2023.12.31 현재,"16,201,439,000,000",제 21 기,2022.12.31 현재,"15,834,021,000,000",17,KRW
8,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,BS,재무상태표,자본총계,...,2024.12.31 현재,"25,211,664,000,000",제 22 기,2023.12.31 현재,"23,498,536,000,000",제 21 기,2022.12.31 현재,"22,491,997,000,000",21,KRW
9,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,매출액,...,2024.01.01 ~ 2024.12.31,"87,728,182,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"82,262,664,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"82,521,459,000,000",23,KRW
10,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,영업이익,...,2024.01.01 ~ 2024.12.31,"3,419,675,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"3,653,294,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"3,567,327,000,000",25,KRW
11,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,...,2024.01.01 ~ 2024.12.31,"1,335,795,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"2,014,897,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"2,570,407,000,000",27,KRW
12,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,당기순이익,...,2024.01.01 ~ 2024.12.31,"591,365,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,150,611,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"1,863,123,000,000",29,KRW
13,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,당기순이익(손실),...,2024.01.01 ~ 2024.12.31,"591,365,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,150,611,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"1,863,123,000,000",61,KRW
14,20250317001029,11011,2024,00401731,066570,CFS,연결재무제표,IS,손익계산서,총포괄손익,...,2024.01.01 ~ 2024.12.31,"2,067,679,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,245,113,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"2,609,456,000,000",63,KRW
15,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,유동자산,...,2024.12.31 현재,"11,936,997,000,000",제 22 기,2023.12.31 현재,"10,757,937,000,000",제 21 기,2022.12.31 현재,"9,119,623,000,000",2,KRW
16,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,비유동자산,...,2024.12.31 현재,"22,961,485,000,000",제 22 기,2023.12.31 현재,"20,989,616,000,000",제 21 기,2022.12.31 현재,"19,593,191,000,000",4,KRW
17,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,자산총계,...,2024.12.31 현재,"34,898,482,000,000",제 22 기,2023.12.31 현재,"31,747,553,000,000",제 21 기,2022.12.31 현재,"28,712,814,000,000",6,KRW
18,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,유동부채,...,2024.12.31 현재,"14,608,535,000,000",제 22 기,2023.12.31 현재,"13,233,469,000,000",제 21 기,2022.12.31 현재,"12,060,574,000,000",8,KRW
19,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,비유동부채,...,2024.12.31 현재,"8,812,896,000,000",제 22 기,2023.12.31 현재,"7,998,537,000,000",제 21 기,2022.12.31 현재,"6,763,211,000,000",10,KRW
20,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,부채총계,...,2024.12.31 현재,"23,421,431,000,000",제 22 기,2023.12.31 현재,"21,232,006,000,000",제 21 기,2022.12.31 현재,"18,823,785,000,000",12,KRW
21,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,자본금,...,2024.12.31 현재,"904,169,000,000",제 22 기,2023.12.31 현재,"904,169,000,000",제 21 기,2022.12.31 현재,"904,169,000,000",15,KRW
22,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,이익잉여금,...,2024.12.31 현재,"7,539,176,000,000",제 22 기,2023.12.31 현재,"6,566,223,000,000",제 21 기,2022.12.31 현재,"5,890,737,000,000",19,KRW
23,20250317001029,11011,2024,00401731,066570,OFS,재무제표,BS,재무상태표,자본총계,...,2024.12.31 현재,"11,477,051,000,000",제 22 기,2023.12.31 현재,"10,515,547,000,000",제 21 기,2022.12.31 현재,"9,889,029,000,000",22,KRW
24,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,매출액,...,2024.01.01 ~ 2024.12.31,"30,762,552,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"28,868,175,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"27,775,732,000,000",24,KRW
25,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,영업이익,...,2024.01.01 ~ 2024.12.31,"558,964,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"686,807,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"134,996,000,000",26,KRW
26,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,...,2024.01.01 ~ 2024.12.31,"1,108,827,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,361,326,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"1,055,303,000,000",28,KRW
27,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,당기순이익,...,2024.01.01 ~ 2024.12.31,"1,136,633,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,004,096,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"854,963,000,000",30,KRW
28,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,당기순이익(손실),...,2024.01.01 ~ 2024.12.31,"1,136,633,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"1,004,096,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"854,963,000,000",62,KRW
29,20250317001029,11011,2024,00401731,066570,OFS,재무제표,IS,손익계산서,총포괄손익,...,2024.01.01 ~ 2024.12.31,"1,196,449,000,000",제 22 기,2023.01.01 ~ 2023.12.31,"753,423,000,000",제 21 기,2022.01.01 ~ 2022.12.31,"1,152,689,000,000",64,KRW

In [23]:
result = result.loc[result["fs_nm"] == "연결재무제표"]
result = result.loc[result["account_nm"].isin(["당기순이익" , "영업이익" , "매출액"])]
result = result.loc[:,["account_nm", "fs_nm" , "thstrm_dt" , "thstrm_amount"]]
display(result)

   account_nm   fs_nm                thstrm_dt       thstrm_amount
9         매출액  연결재무제표  2024.01.01 ~ 2024.12.31  87,728,182,000,000
10       영업이익  연결재무제표  2024.01.01 ~ 2024.12.31   3,419,675,000,000
12      당기순이익  연결재무제표  2024.01.01 ~ 2024.12.31     591,365,000,000